apiVersion: apps/v1
kind: Deployment
metadata: 
  name: decker-k8s-sbprojpoc-depl
  labels:
    app: docker-k8s-deployment-cfg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-deployment-cfg
  template:
    metadata:
      labels:
        app: docker-k8s-deployment-cfg
    spec:
      containers:
      - name: docker-k8s-deployment-cfg
        image: scnxvagarwala/sbprojpoc
        ports:
        - containerPort: 8080